version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.22
    commands:
      - echo installing dependencies..
      - go mod tidy
  build:
    commands:
      - echo Build started
      - go build -o bin/usersvc ./usersvc/cmd
  post_build:
    commands:
      - echo Build completed 